name: redis-shift-register
services:
  redis:
    image: redis:latest
    container_name: redis-shift-register
    hostname: redis-shift-register
    ports:
      - "6379:6379"
    volumes:
      - redis-shift-register-data:/data
    command: redis-server --timeout 0 --save 60 1 --loglevel debug
    restart: unless-stopped

volumes:
  redis-shift-register-data:
    name: redis-shift-register-data